<<<<<<< HEAD
# Generated by Django 4.1.2 on 2022-10-20 14:28
=======
# Generated by Django 4.1.2 on 2022-10-20 19:32
>>>>>>> 673e1b3429468cbcad61e4030ccddf964a878ebe

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=30)),
<<<<<<< HEAD
=======
                ('image', models.ImageField(blank=True, upload_to='recipe_pics')),
>>>>>>> 673e1b3429468cbcad61e4030ccddf964a878ebe
                ('youtube_url', models.URLField(max_length=100)),
                ('ingred', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
