<<<<<<< HEAD
# Generated by Django 4.1.2 on 2022-10-20 14:28

from django.conf import settings
from django.db import migrations, models
=======
# Generated by Django 4.1.2 on 2022-10-20 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
>>>>>>> 673e1b3429468cbcad61e4030ccddf964a878ebe


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipe', '0001_initial'),
=======
        ('recipe', '0001_initial'),
        ('post', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
>>>>>>> 673e1b3429468cbcad61e4030ccddf964a878ebe
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
<<<<<<< HEAD
            name='like_authors',
            field=models.ManyToManyField(related_name='like_recipes', to=settings.AUTH_USER_MODEL),
        ),
=======
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recipe',
            name='like_authors',
            field=models.ManyToManyField(related_name='like_recipes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recipe',
            name='post',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='post.post'),
        ),
>>>>>>> 673e1b3429468cbcad61e4030ccddf964a878ebe
    ]
