# Generated by Django 4.1.2 on 2022-10-21 11:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipe', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='like_authors',
            field=models.ManyToManyField(related_name='like_recipes', to=settings.AUTH_USER_MODEL),
        ),
    ]
